# Generated by Django 5.0.4 on 2024-07-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_categoryproduct_measure_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryproduct',
            old_name='delete_date',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='categoryproduct',
            old_name='modifed_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='historicalcategoryproduct',
            old_name='delete_date',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='historicalcategoryproduct',
            old_name='modifed_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='historicalindicator',
            old_name='delete_date',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='historicalindicator',
            old_name='modifed_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='historicalmeasureunit',
            old_name='delete_date',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='historicalmeasureunit',
            old_name='modifed_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='delete_date',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='modifed_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='delete_date',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='modifed_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='measureunit',
            old_name='delete_date',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='measureunit',
            old_name='modifed_date',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='delete_date',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='modifed_date',
            new_name='modified_date',
        ),
    ]
